services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
    volumes:
      - /home/ubuntu/jenkins-backup:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      TZ: "Asia/Seoul"

  mysql:
    image: mysql:8.0.38
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - /mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  spring:
    container_name: spring
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/configure:/app/configure
    depends_on:
      - mysql
      - redis

  fastapi:
    container_name: fastapi
    build:
      context: ./AI
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /home/ubuntu/configure:/app/configure
    environment:
      - ENV_FILE_PATH: "/app/configure/.env"
    depends_on:
      - mysql
      - redis

networks:
  default:
    name: welight