spring:
  main:
    web-application-type: servlet
    allow-circular-references: true
    allow-bean-definition-overriding: true

  profiles:
    include: s3, db, security

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 생성 전략 (update, create, create-drop 등)
    show-sql: true  # SQL 쿼리 로깅 여부
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅 여부

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    root: INFO    # 전체 애플리케이션의 기본 로그 레벨 설정
    com.d209.welight: DEBUG   # 특정 패키지에 대한 로그 레벨 설정
    org.springframework.web: INFO   # 스프링 웹 관련 로그 레벨 설정



